In [2]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3, 4, 5],
               [6, 7, 8, 9, 10],
               [11, 12, 13, 14, 15],
               [16, 17, 18, 19, 20],
               [21, 22, 23, 24, 25],
               [26, 27, 28, 29, 30]])

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [4]:
print("Jawaban untuk warna Biru")
print(arr[2:4, :2])

Jawaban untuk warna Biru
[[11 12]
 [16 17]]


In [5]:
print("Jawaban untuk warna Merah")
print(arr[[0, 4, 5], 3:])

Jawaban untuk warna Merah
[[ 4  5]
 [24 25]
 [29 30]]


In [7]:
print("Jawaban untuk warna Hijau")
print(arr[(0,1,2,3),(1,2,3,4)])

Jawaban untuk warna Hijau
[ 2  8 14 20]
