In [9]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('/content/sample_data/Homework - Data Preprocessing.csv')
df

Animal   Age    Worth Friendly
0    Cat   NaN  72000.0       No
1    Dog  17.0      NaN      Yes
2  Moose   6.0  54000.0       No
3    NaN   8.0  61000.0       No
4  Moose   4.0      NaN      Yes
5    Cat  15.0  58000.0      Yes
6    Dog   NaN  52000.0       No
7    Cat  12.0      NaN      Yes
8  Moose   NaN  83000.0       No
9    Cat   7.0  67000.0      Yes

In [6]:
df.isnull().sum()

Animal      1
Age         3
Worth       3
Friendly    0
dtype: int64

In [8]:
df.Animal.value_counts()

Cat      4
Moose    3
Dog      2
Name: Animal, dtype: int64

In [17]:
df['Animal'].fillna(df['Animal'].mode()[0], inplace=True)

In [11]:
df.describe()

Age         Worth
count   7.000000      7.000000
mean    9.857143  63857.142857
std     4.879500  10976.164652
min     4.000000  52000.000000
25%     6.500000  56000.000000
50%     8.000000  61000.000000
75%    13.500000  69500.000000
max    17.000000  83000.000000

In [16]:
df['Age'].fillna(df['Age'].median(), inplace=True)

In [15]:
df['Worth'].fillna(df['Worth'].median(), inplace=True)

In [18]:
df.isnull().sum()

Animal      0
Age         0
Worth       0
Friendly    0
dtype: int64

In [19]:
X = df[['Animal', 'Age', 'Worth']].values
y = df['Friendly'].values

In [21]:
from sklearn.preprocessing import StandardScaler

df['Age_std'] = StandardScaler().fit_transform(df['Age'].values.reshape(len(df), 1))
df['Worth_std'] = StandardScaler().fit_transform(df['Worth'].values.reshape(len(df), 1))

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],
                       remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [23]:
X

array([[1.0, 0.0, 0.0, 8.0, 72000.0],
       [0.0, 1.0, 0.0, 17.0, 61000.0],
       [0.0, 0.0, 1.0, 6.0, 54000.0],
       [1.0, 0.0, 0.0, 8.0, 61000.0],
       [0.0, 0.0, 1.0, 4.0, 61000.0],
       [1.0, 0.0, 0.0, 15.0, 58000.0],
       [0.0, 1.0, 0.0, 8.0, 52000.0],
       [1.0, 0.0, 0.0, 12.0, 61000.0],
       [0.0, 0.0, 1.0, 8.0, 83000.0],
       [1.0, 0.0, 0.0, 7.0, 67000.0]], dtype=object)

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [25]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [27]:
X_train

array([[1.0, 0.0, 0.0, 15.0, 58000.0],
       [1.0, 0.0, 0.0, 8.0, 72000.0],
       [1.0, 0.0, 0.0, 12.0, 61000.0],
       [0.0, 0.0, 1.0, 6.0, 54000.0],
       [1.0, 0.0, 0.0, 8.0, 61000.0],
       [0.0, 1.0, 0.0, 8.0, 52000.0],
       [1.0, 0.0, 0.0, 7.0, 67000.0],
       [0.0, 0.0, 1.0, 8.0, 83000.0]], dtype=object)

In [28]:
X_test

array([[0.0, 0.0, 1.0, 4.0, 61000.0],
       [0.0, 1.0, 0.0, 17.0, 61000.0]], dtype=object)

In [29]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
sc = StandardScaler()
mm = MinMaxScaler()
sc.fit_transform(X_train)

array([[ 0.77459667, -0.37796447, -0.57735027,  2.15526362, -0.57576631],
       [ 0.77459667, -0.37796447, -0.57735027, -0.3592106 ,  0.88982067],
       [ 0.77459667, -0.37796447, -0.57735027,  1.07763181, -0.26171196],
       [-1.29099445, -0.37796447,  1.73205081, -1.07763181, -0.99450545],
       [ 0.77459667, -0.37796447, -0.57735027, -0.3592106 , -0.26171196],
       [-1.29099445,  2.64575131, -0.57735027, -0.3592106 , -1.20387502],
       [ 0.77459667, -0.37796447, -0.57735027, -0.71842121,  0.36639675],
       [-1.29099445, -0.37796447,  1.73205081, -0.3592106 ,  2.0413533 ]])

In [30]:
mm.fit_transform(X_train)

array([[1.        , 0.        , 0.        , 1.        , 0.19354839],
       [1.        , 0.        , 0.        , 0.22222222, 0.64516129],
       [1.        , 0.        , 0.        , 0.66666667, 0.29032258],
       [0.        , 0.        , 1.        , 0.        , 0.06451613],
       [1.        , 0.        , 0.        , 0.22222222, 0.29032258],
       [0.        , 1.        , 0.        , 0.22222222, 0.        ],
       [1.        , 0.        , 0.        , 0.11111111, 0.48387097],
       [0.        , 0.        , 1.        , 0.22222222, 1.        ]])